#server:
#  port: 7101
#spring:
#  application:
#    name: microcloud-config
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/zhuoufei/microconfig.git

spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: microconfig-test-dev
---
spring:
  profiles: default
  application:
    name: microconfig-test-default